//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Endereco
    {
        public int ID_Endereco { get; set; }
        public int ID_AutorCliente { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
    
        public virtual TB_Autor TB_Autor { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
