//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Livro_Autor
    {
        public int ID_Livro_Autor { get; set; }
        public int ID_Livro { get; set; }
        public int ID_Autor { get; set; }
    
        public virtual TB_Autor TB_Autor { get; set; }
        public virtual TB_Livro TB_Livro { get; set; }
    }
}
