//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPIcomplet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Carrinho
    {
        public int ID_Carrinho { get; set; }
        public int ID_Compra { get; set; }
        public int ID_Livro { get; set; }
        public int Quantidade_Livro { get; set; }
        public decimal Preco_Total_Livro { get; set; }
    
        public virtual TB_Compra TB_Compra { get; set; }
        public virtual TB_Livro TB_Livro { get; set; }
    }
}
