//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPIcomplet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cupom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Cupom()
        {
            this.TB_Cupom_Livro = new HashSet<TB_Cupom_Livro>();
            this.TB_Cupom_Pessoa = new HashSet<TB_Cupom_Pessoa>();
        }
    
        public int ID_Cupom { get; set; }
        public decimal Valor_Desconto { get; set; }
        public string Nome { get; set; }
        public System.DateTime Data_ini { get; set; }
        public System.DateTime Data_fim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cupom_Livro> TB_Cupom_Livro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cupom_Pessoa> TB_Cupom_Pessoa { get; set; }
    }
}
