//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPIcomplet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cupom_Livro
    {
        public int ID_Cupom_Livro { get; set; }
        public int ID_Cupom { get; set; }
        public int ID_Livro { get; set; }
    
        public virtual TB_Cupom TB_Cupom { get; set; }
        public virtual TB_Livro TB_Livro { get; set; }
    }
}
