//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPIcomplet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Livro()
        {
            this.TB_Carrinho = new HashSet<TB_Carrinho>();
            this.TB_Cupom_Livro = new HashSet<TB_Cupom_Livro>();
            this.TB_Estoque = new HashSet<TB_Estoque>();
            this.TB_Livro_Autor = new HashSet<TB_Livro_Autor>();
        }
    
        public int ID_Livro { get; set; }
        public string Titulo { get; set; }
        public string Descrição { get; set; }
        public decimal Preco { get; set; }
        public System.DateTime Data_Publicacao { get; set; }
        public int Numero_Paginas { get; set; }
        public string Ilustrador { get; set; }
        public string Tipo_Livro { get; set; }
        public string ISBN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Carrinho> TB_Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cupom_Livro> TB_Cupom_Livro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Estoque> TB_Estoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Livro_Autor> TB_Livro_Autor { get; set; }
    }
}
