//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPIcomplet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Telefone
    {
        public int ID_Telefone { get; set; }
        public string Tipo_Telefone { get; set; }
        public string Numero { get; set; }
        public int ID_AutorCliente { get; set; }
    
        public virtual TB_Autor TB_Autor { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
