// <auto-generated />
namespace EditoraAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Banco23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco23));
        
        string IMigrationMetadata.Id
        {
            get { return "201912032023225_Banco23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
