//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EditoraEntities : DbContext
    {
        public EditoraEntities()
            : base("name=EditoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_Autor> TB_Autor { get; set; }
        public virtual DbSet<TB_Carrinho> TB_Carrinho { get; set; }
        public virtual DbSet<TB_Cliente> TB_Cliente { get; set; }
        public virtual DbSet<TB_Compra> TB_Compra { get; set; }
        public virtual DbSet<TB_Cupom> TB_Cupom { get; set; }
        public virtual DbSet<TB_Cupom_Livro> TB_Cupom_Livro { get; set; }
        public virtual DbSet<TB_Cupom_Pessoa> TB_Cupom_Pessoa { get; set; }
        public virtual DbSet<TB_Endereco> TB_Endereco { get; set; }
        public virtual DbSet<TB_Escola> TB_Escola { get; set; }
        public virtual DbSet<TB_Estoque> TB_Estoque { get; set; }
        public virtual DbSet<TB_Livraria> TB_Livraria { get; set; }
        public virtual DbSet<TB_Livro> TB_Livro { get; set; }
        public virtual DbSet<TB_Livro_Autor> TB_Livro_Autor { get; set; }
        public virtual DbSet<TB_Pessoa> TB_Pessoa { get; set; }
        public virtual DbSet<TB_RedeSocial> TB_RedeSocial { get; set; }
        public virtual DbSet<TB_Telefone> TB_Telefone { get; set; }
        public virtual DbSet<TB_Tipo> TB_Tipo { get; set; }
    }
}
