//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Escola
    {
        public int ID_Escola { get; set; }
        public int ID_Cliente { get; set; }
        public string Nome_Instituicao { get; set; }
        public int CNPJ { get; set; }
        public string Responsavel { get; set; }
        public string Livro_Adotado { get; set; }
        public string Serie_Adotada { get; set; }
        public System.DateTime Dt_Adotacao { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
