//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Livraria
    {
        public int ID_Livraria { get; set; }
        public int ID_Cliente { get; set; }
        public string CNPJ { get; set; }
        public string Tipo_consignacao { get; set; }
        public string Nome { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
