//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Pessoa()
        {
            this.TB_Cupom_Pessoa = new HashSet<TB_Cupom_Pessoa>();
        }
    
        public int ID_Pessoa { get; set; }
        public int ID_Cliente { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public decimal Desconto { get; set; }
        public string Tipo_Pessoa { get; set; }
        public string Sexo { get; set; }
        public System.DateTime data_nascimento { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cupom_Pessoa> TB_Cupom_Pessoa { get; set; }
    }
}
