//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditoraAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RedeSocial
    {
        public int ID_RedeSocial { get; set; }
        public int ID_AutorCliente { get; set; }
        public string Email { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
    
        public virtual TB_Autor TB_Autor { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
